# Generated by Django 3.0.6 on 2020-06-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
