# Generated by Django 3.0.6 on 2020-06-05 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('exam_name', models.CharField(max_length=100)),
                ('exam_code', models.IntegerField(primary_key=True, serialize=False)),
                ('exam_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registration_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('data_of_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examiner.Exams')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options1', models.TextField()),
                ('options2', models.TextField()),
                ('options3', models.TextField()),
                ('options4', models.TextField()),
                ('answer', models.TextField()),
                ('question_of_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examiner.Exams')),
            ],
        ),
        migrations.AddField(
            model_name='exams',
            name='subject_of_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examiner.Subjects'),
        ),
    ]
