# Generated by Django 3.0.6 on 2020-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='exam_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
