# Generated by Django 3.0.6 on 2020-06-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examiner', '0002_auto_20200607_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_data',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
